modLoader="javafml"
loaderVersion="[43,)"
license="LGPL-3.0"
[[mods]]
modId="expatternprovider"
issueTrackerURL="https://github.com/GlodBlock/ExtendedAE/issues"
displayURL="https://github.com/GlodBlock/ExtendedAE"
version="1.19-0.1.3-forge"
displayName="ExtendedAE"
authors="GlodBlock"
logoFile="logo.png"

description='''
Add some QoL extended contents for AE2
'''
[[dependencies.expatternprovider]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.expatternprovider]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.expatternprovider]]
    modId="ae2"
    mandatory=true
    versionRange="[12.9.5,)"
    ordering="AFTER"
    side="BOTH"