modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
[[mods]]
modId="ae2netanalyser"
issueTrackerURL="https://github.com/GlodBlock/ExtendedAE/issues"
displayURL="https://github.com/GlodBlock/ExtendedAE"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
credits="bdew"

description='''${mod_description}'''
[[dependencies.ae2netanalyser]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.ae2netanalyser]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.ae2netanalyser]]
    modId="ae2"
    mandatory=true
    versionRange="[15.0.12,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.ae2netanalyser]]
    modId="glodium"
    mandatory=true
    versionRange="[1.2,)"
    ordering="AFTER"
    side="BOTH"