modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
[[mods]]
modId="expatternprovider"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
logoFile="logo.png"

description='''${mod_description}'''
[[dependencies.expatternprovider]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.expatternprovider]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.expatternprovider]]
    modId="ae2"
    mandatory=true
    versionRange="[15.0.4,)"
    ordering="AFTER"
    side="BOTH"