modLoader="javafml"
loaderVersion="[43,)"
license="LGPL-3.0"
[[mods]]
modId="eterminal"
version="1.19-0.0.1-forge"
displayName="Enhanced Terminal"
authors="GlodBlock"
logoFile="logo.png"

description='''
Add better terminals for AE2
'''
[[dependencies.eterminal]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.eterminal]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.eterminal]]
    modId="ae2"
    mandatory=true
    versionRange="[12.9.5,)"
    ordering="AFTER"
    side="BOTH"