modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
[[mods]]
    modId="ae2netanalyser"
    issueTrackerURL="https://github.com/GlodBlock/ExtendedAE/issues"
    displayURL="https://github.com/GlodBlock/ExtendedAE"
    version="${mod_version}"
    displayName="${mod_name}"
    authors="${mod_authors}"
    credits="bdew"
    logoFile="logo.png"
    description='''${mod_description}'''

[[dependencies.ae2netanalyser]]
    modId="neoforge"
    type="REQUIRED"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.ae2netanalyser]]
    modId="minecraft"
    type="REQUIRED"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.ae2netanalyser]]
    modId="ae2"
    type="REQUIRED"
    versionRange="[19.0.7-alpha,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.ae2netanalyser]]
    modId="glodium"
    type="REQUIRED"
    versionRange="[1.21-1.2-neoforge,)"
    ordering="AFTER"
    side="BOTH"