modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
[[mods]]
    modId="appflux"
    issueTrackerURL="https://github.com/GlodBlock/ExtendedAE/issues"
    displayURL="https://github.com/GlodBlock/ExtendedAE"
    version="${mod_version}"
    displayName="${mod_name}"
    authors="${mod_authors}"
    logoFile="logo.png"
    credits="Ridanisaurus for the new textures."
    description='''${mod_description}'''

[[mixins]]
    config="mixins.appflux.json"

[[dependencies.appflux]]
    modId="neoforge"
    type="REQUIRED"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.appflux]]
    modId="minecraft"
    type="REQUIRED"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.appflux]]
    modId="ae2"
    type="REQUIRED"
    versionRange="[19.0.12-alpha,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.appflux]]
    modId="glodium"
    type="REQUIRED"
    versionRange="[1.21-1.1-neoforge,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.appflux]]
    modId="mekanism"
    type="OPTIONAL"
    versionRange="*"
    ordering="AFTER"
    side="BOTH"